import type { Metadata } from 'next';
import { Geist, Geist_Mono } from 'next/font/google';
import cn from 'classnames';
import './globals.css';
import Script from 'next/script';

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
});

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
  icons: {
    icon: process.env.NODE_ENV === 'production' ? 'https://swdbyouthful.github.io/swdb/swdb.ico' : '/swdb.ico',
  },
  robots: {
    index: false,
    follow: false,
    googleBot: {
      index: false,
      follow: false,
    },
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <head>
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="수원동부교회" />
        <meta name="theme-color" content="#000000" />
        <meta name="robots" content="noindex, nofollow" />
        <meta name="googlebot" content="noindex, nofollow" />

        <meta property="og:title" content="수원동부교회" />
        <meta property="og:description" content="수원동부교회" />
        {/* <meta property="og:image" content="/swdb/og-image.png" /> */}
        <meta property="og:url" content="https://swdbyouthful.github.io/swdb/" />
        <meta property="og:type" content="website" />

        <link rel="manifest" href="/swdb/manifest.json" />
      </head>
      <body className={cn(geistSans.variable, geistMono.variable, 'h-dvh overflow-y-auto antialiased')}>
        {!!process.env.NAVER_MAP_CLIENT_ID && (
          <Script
            type="text/javascript"
            strategy="beforeInteractive"
            src={`https://oapi.map.naver.com/openapi/v3/maps.js?ncpKeyId=${process.env.NAVER_MAP_CLIENT_ID}`}
          />
        )}
        {children}
      </body>
    </html>
  );
}
